// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonMessagesProtoDef.proto

package com.haloai.hud.proto.v2;

public final class CommonMessagesProtoDef {
  private CommonMessagesProtoDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.haloai.hud.proto.v2.RecorderTypeProto}
   */
  public enum RecorderTypeProto
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOOP_VIDEO = 1;</code>
     */
    LOOP_VIDEO(0, 1),
    /**
     * <code>LOCK_VIDEO = 2;</code>
     */
    LOCK_VIDEO(1, 2),
    /**
     * <code>WONDERFUL_VIDEO = 3;</code>
     */
    WONDERFUL_VIDEO(2, 3),
    /**
     * <code>EMERGENCY_VIDEO = 4;</code>
     */
    EMERGENCY_VIDEO(3, 4),
    ;

    /**
     * <code>LOOP_VIDEO = 1;</code>
     */
    public static final int LOOP_VIDEO_VALUE = 1;
    /**
     * <code>LOCK_VIDEO = 2;</code>
     */
    public static final int LOCK_VIDEO_VALUE = 2;
    /**
     * <code>WONDERFUL_VIDEO = 3;</code>
     */
    public static final int WONDERFUL_VIDEO_VALUE = 3;
    /**
     * <code>EMERGENCY_VIDEO = 4;</code>
     */
    public static final int EMERGENCY_VIDEO_VALUE = 4;


    public final int getNumber() { return value; }

    public static RecorderTypeProto valueOf(int value) {
      switch (value) {
        case 1: return LOOP_VIDEO;
        case 2: return LOCK_VIDEO;
        case 3: return WONDERFUL_VIDEO;
        case 4: return EMERGENCY_VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RecorderTypeProto>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RecorderTypeProto>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RecorderTypeProto>() {
            public RecorderTypeProto findValueByNumber(int number) {
              return RecorderTypeProto.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.haloai.hud.proto.v2.CommonMessagesProtoDef.getDescriptor().getEnumTypes().get(0);
    }

    private static final RecorderTypeProto[] VALUES = values();

    public static RecorderTypeProto valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private RecorderTypeProto(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.haloai.hud.proto.v2.RecorderTypeProto)
  }

  public interface HudDataDefineProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.haloai.hud.proto.v2.HudDataDefineProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 hud_data_type = 1;</code>
     */
    boolean hasHudDataType();
    /**
     * <code>required int32 hud_data_type = 1;</code>
     */
    int getHudDataType();

    /**
     * <code>optional bool bool_param = 2;</code>
     */
    boolean hasBoolParam();
    /**
     * <code>optional bool bool_param = 2;</code>
     */
    boolean getBoolParam();

    /**
     * <code>optional int32 int_param = 3;</code>
     */
    boolean hasIntParam();
    /**
     * <code>optional int32 int_param = 3;</code>
     */
    int getIntParam();

    /**
     * <code>optional double double_param = 4;</code>
     */
    boolean hasDoubleParam();
    /**
     * <code>optional double double_param = 4;</code>
     */
    double getDoubleParam();

    /**
     * <code>optional string extra_param = 5;</code>
     */
    boolean hasExtraParam();
    /**
     * <code>optional string extra_param = 5;</code>
     */
    java.lang.String getExtraParam();
    /**
     * <code>optional string extra_param = 5;</code>
     */
    com.google.protobuf.ByteString
        getExtraParamBytes();

    /**
     * <code>optional string extra_param1 = 6;</code>
     */
    boolean hasExtraParam1();
    /**
     * <code>optional string extra_param1 = 6;</code>
     */
    java.lang.String getExtraParam1();
    /**
     * <code>optional string extra_param1 = 6;</code>
     */
    com.google.protobuf.ByteString
        getExtraParam1Bytes();
  }
  /**
   * Protobuf type {@code com.haloai.hud.proto.v2.HudDataDefineProto}
   *
   * <pre>
   *设置的消息定义
   * </pre>
   */
  public static final class HudDataDefineProto extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.haloai.hud.proto.v2.HudDataDefineProto)
      HudDataDefineProtoOrBuilder {
    // Use HudDataDefineProto.newBuilder() to construct.
    private HudDataDefineProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HudDataDefineProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HudDataDefineProto defaultInstance;
    public static HudDataDefineProto getDefaultInstance() {
      return defaultInstance;
    }

    public HudDataDefineProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HudDataDefineProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hudDataType_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              boolParam_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              intParam_ = input.readInt32();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              doubleParam_ = input.readDouble();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              extraParam_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              extraParam1_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.haloai.hud.proto.v2.CommonMessagesProtoDef.internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.haloai.hud.proto.v2.CommonMessagesProtoDef.internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto.class, com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto.Builder.class);
    }

    public static com.google.protobuf.Parser<HudDataDefineProto> PARSER =
        new com.google.protobuf.AbstractParser<HudDataDefineProto>() {
      public HudDataDefineProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HudDataDefineProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HudDataDefineProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HUD_DATA_TYPE_FIELD_NUMBER = 1;
    private int hudDataType_;
    /**
     * <code>required int32 hud_data_type = 1;</code>
     */
    public boolean hasHudDataType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 hud_data_type = 1;</code>
     */
    public int getHudDataType() {
      return hudDataType_;
    }

    public static final int BOOL_PARAM_FIELD_NUMBER = 2;
    private boolean boolParam_;
    /**
     * <code>optional bool bool_param = 2;</code>
     */
    public boolean hasBoolParam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool bool_param = 2;</code>
     */
    public boolean getBoolParam() {
      return boolParam_;
    }

    public static final int INT_PARAM_FIELD_NUMBER = 3;
    private int intParam_;
    /**
     * <code>optional int32 int_param = 3;</code>
     */
    public boolean hasIntParam() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 int_param = 3;</code>
     */
    public int getIntParam() {
      return intParam_;
    }

    public static final int DOUBLE_PARAM_FIELD_NUMBER = 4;
    private double doubleParam_;
    /**
     * <code>optional double double_param = 4;</code>
     */
    public boolean hasDoubleParam() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double double_param = 4;</code>
     */
    public double getDoubleParam() {
      return doubleParam_;
    }

    public static final int EXTRA_PARAM_FIELD_NUMBER = 5;
    private java.lang.Object extraParam_;
    /**
     * <code>optional string extra_param = 5;</code>
     */
    public boolean hasExtraParam() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string extra_param = 5;</code>
     */
    public java.lang.String getExtraParam() {
      java.lang.Object ref = extraParam_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          extraParam_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string extra_param = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExtraParamBytes() {
      java.lang.Object ref = extraParam_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extraParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRA_PARAM1_FIELD_NUMBER = 6;
    private java.lang.Object extraParam1_;
    /**
     * <code>optional string extra_param1 = 6;</code>
     */
    public boolean hasExtraParam1() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string extra_param1 = 6;</code>
     */
    public java.lang.String getExtraParam1() {
      java.lang.Object ref = extraParam1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          extraParam1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string extra_param1 = 6;</code>
     */
    public com.google.protobuf.ByteString
        getExtraParam1Bytes() {
      java.lang.Object ref = extraParam1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extraParam1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      hudDataType_ = 0;
      boolParam_ = false;
      intParam_ = 0;
      doubleParam_ = 0D;
      extraParam_ = "";
      extraParam1_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHudDataType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, hudDataType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, boolParam_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, intParam_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, doubleParam_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getExtraParamBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getExtraParam1Bytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, hudDataType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, boolParam_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, intParam_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, doubleParam_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getExtraParamBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getExtraParam1Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.haloai.hud.proto.v2.HudDataDefineProto}
     *
     * <pre>
     *设置的消息定义
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.haloai.hud.proto.v2.HudDataDefineProto)
        com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.haloai.hud.proto.v2.CommonMessagesProtoDef.internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.haloai.hud.proto.v2.CommonMessagesProtoDef.internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto.class, com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto.Builder.class);
      }

      // Construct using com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        hudDataType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        boolParam_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        intParam_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        doubleParam_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        extraParam_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        extraParam1_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.haloai.hud.proto.v2.CommonMessagesProtoDef.internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_descriptor;
      }

      public com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto getDefaultInstanceForType() {
        return com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto.getDefaultInstance();
      }

      public com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto build() {
        com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto buildPartial() {
        com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto result = new com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hudDataType_ = hudDataType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.boolParam_ = boolParam_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.intParam_ = intParam_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.doubleParam_ = doubleParam_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.extraParam_ = extraParam_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.extraParam1_ = extraParam1_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto) {
          return mergeFrom((com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto other) {
        if (other == com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto.getDefaultInstance()) return this;
        if (other.hasHudDataType()) {
          setHudDataType(other.getHudDataType());
        }
        if (other.hasBoolParam()) {
          setBoolParam(other.getBoolParam());
        }
        if (other.hasIntParam()) {
          setIntParam(other.getIntParam());
        }
        if (other.hasDoubleParam()) {
          setDoubleParam(other.getDoubleParam());
        }
        if (other.hasExtraParam()) {
          bitField0_ |= 0x00000010;
          extraParam_ = other.extraParam_;
          onChanged();
        }
        if (other.hasExtraParam1()) {
          bitField0_ |= 0x00000020;
          extraParam1_ = other.extraParam1_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHudDataType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.haloai.hud.proto.v2.CommonMessagesProtoDef.HudDataDefineProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int hudDataType_ ;
      /**
       * <code>required int32 hud_data_type = 1;</code>
       */
      public boolean hasHudDataType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 hud_data_type = 1;</code>
       */
      public int getHudDataType() {
        return hudDataType_;
      }
      /**
       * <code>required int32 hud_data_type = 1;</code>
       */
      public Builder setHudDataType(int value) {
        bitField0_ |= 0x00000001;
        hudDataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 hud_data_type = 1;</code>
       */
      public Builder clearHudDataType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hudDataType_ = 0;
        onChanged();
        return this;
      }

      private boolean boolParam_ ;
      /**
       * <code>optional bool bool_param = 2;</code>
       */
      public boolean hasBoolParam() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool bool_param = 2;</code>
       */
      public boolean getBoolParam() {
        return boolParam_;
      }
      /**
       * <code>optional bool bool_param = 2;</code>
       */
      public Builder setBoolParam(boolean value) {
        bitField0_ |= 0x00000002;
        boolParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool bool_param = 2;</code>
       */
      public Builder clearBoolParam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        boolParam_ = false;
        onChanged();
        return this;
      }

      private int intParam_ ;
      /**
       * <code>optional int32 int_param = 3;</code>
       */
      public boolean hasIntParam() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 int_param = 3;</code>
       */
      public int getIntParam() {
        return intParam_;
      }
      /**
       * <code>optional int32 int_param = 3;</code>
       */
      public Builder setIntParam(int value) {
        bitField0_ |= 0x00000004;
        intParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 int_param = 3;</code>
       */
      public Builder clearIntParam() {
        bitField0_ = (bitField0_ & ~0x00000004);
        intParam_ = 0;
        onChanged();
        return this;
      }

      private double doubleParam_ ;
      /**
       * <code>optional double double_param = 4;</code>
       */
      public boolean hasDoubleParam() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double double_param = 4;</code>
       */
      public double getDoubleParam() {
        return doubleParam_;
      }
      /**
       * <code>optional double double_param = 4;</code>
       */
      public Builder setDoubleParam(double value) {
        bitField0_ |= 0x00000008;
        doubleParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double double_param = 4;</code>
       */
      public Builder clearDoubleParam() {
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleParam_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object extraParam_ = "";
      /**
       * <code>optional string extra_param = 5;</code>
       */
      public boolean hasExtraParam() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string extra_param = 5;</code>
       */
      public java.lang.String getExtraParam() {
        java.lang.Object ref = extraParam_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            extraParam_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string extra_param = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExtraParamBytes() {
        java.lang.Object ref = extraParam_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extraParam_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string extra_param = 5;</code>
       */
      public Builder setExtraParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        extraParam_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string extra_param = 5;</code>
       */
      public Builder clearExtraParam() {
        bitField0_ = (bitField0_ & ~0x00000010);
        extraParam_ = getDefaultInstance().getExtraParam();
        onChanged();
        return this;
      }
      /**
       * <code>optional string extra_param = 5;</code>
       */
      public Builder setExtraParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        extraParam_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object extraParam1_ = "";
      /**
       * <code>optional string extra_param1 = 6;</code>
       */
      public boolean hasExtraParam1() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string extra_param1 = 6;</code>
       */
      public java.lang.String getExtraParam1() {
        java.lang.Object ref = extraParam1_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            extraParam1_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string extra_param1 = 6;</code>
       */
      public com.google.protobuf.ByteString
          getExtraParam1Bytes() {
        java.lang.Object ref = extraParam1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extraParam1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string extra_param1 = 6;</code>
       */
      public Builder setExtraParam1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        extraParam1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string extra_param1 = 6;</code>
       */
      public Builder clearExtraParam1() {
        bitField0_ = (bitField0_ & ~0x00000020);
        extraParam1_ = getDefaultInstance().getExtraParam1();
        onChanged();
        return this;
      }
      /**
       * <code>optional string extra_param1 = 6;</code>
       */
      public Builder setExtraParam1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        extraParam1_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.haloai.hud.proto.v2.HudDataDefineProto)
    }

    static {
      defaultInstance = new HudDataDefineProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.haloai.hud.proto.v2.HudDataDefineProto)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034CommonMessagesProtoDef.proto\022\027com.halo" +
      "ai.hud.proto.v2\"\223\001\n\022HudDataDefineProto\022\025" +
      "\n\rhud_data_type\030\001 \002(\005\022\022\n\nbool_param\030\002 \001(" +
      "\010\022\021\n\tint_param\030\003 \001(\005\022\024\n\014double_param\030\004 \001" +
      "(\001\022\023\n\013extra_param\030\005 \001(\t\022\024\n\014extra_param1\030" +
      "\006 \001(\t*]\n\021RecorderTypeProto\022\016\n\nLOOP_VIDEO" +
      "\020\001\022\016\n\nLOCK_VIDEO\020\002\022\023\n\017WONDERFUL_VIDEO\020\003\022" +
      "\023\n\017EMERGENCY_VIDEO\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_haloai_hud_proto_v2_HudDataDefineProto_descriptor,
        new java.lang.String[] { "HudDataType", "BoolParam", "IntParam", "DoubleParam", "ExtraParam", "ExtraParam1", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
